console.log("Javascript variable");
console.log("-------------------");
var name = "Santhoshini";
console.log(name);
name = ("Santho");
console.log(name);
let age = 50;
console.log(age);
age = 51;
console.log(age);
const id = 22;
console.log(id);
const name1 = "Sheela"
console.log(name1);
const mailid = "santhobas2003@gmail.com";
console.log(mailid);
const contactnumber = 987654321;
console.log(contactnumber);
const aadharnumber = 804678182016;
console.log(aadharnumber);
const pannumber = "PGRST50603X";
console.log(pannumber);
const uannumber = 804678182016;
console.log(uannumber);
let age1 = 20;
console.log(age1);
const gender = "Female";
console.log(gender);
const dateofbirth = "06-05-2003"
console.log(dateofbirth);
let maritalstatus = "Single";
console.log(maritalstatus);
maritalstatus = "Committed";
console.log(maritalstatus);
let company = "WIPRO"
console.log(company);
let branch = "CSE";
console.log(branch);
let department = "Engineering";
console.log(department);
let designation = "JavaDeveloper";
console.log(designation);
let salary = 500000;
console.log(salary);
let role = "Developer";
console.log(role);
let incentive = 333333;
console.log(incentive);
let year_of_experience = "Fresher";
console.log(year_of_experience);
let city = "Chennai";
console.log(city);
let state = "Tamilnadu";
console.log(state);
let country = "India";
console.log(country);
let base = 2;
console.log("base is" +base);
let expo = 3;
console.log("expo is" +expo);
let power = base ** expo;
console.log("power is" +power);
